services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tecnicos
      POSTGRES_PASSWORD: tecnicos
      POSTGRES_DB: tecnicos
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tecnicos -d tecnicos"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    environment:
      PUERTO: ":8080"
      DB_DRIVER: postgres
      DB_DSN: "host=db user=tecnicos password=tecnicos dbname=tecnicos port=5432 sslmode=disable TimeZone=America/Guayaquil"
      JWT_SECRETO: "anthol34"
      STORAGE: sqlc
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata: