// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type Dispositivo struct {
	ID                 int64
	SolicitanteID      int64
	Marca              string
	Modelo             string
	TipoAlmacenamiento string
	RamGb              int64
	SistemaOperativo   string
}

type Solicitante struct {
	ID            int64
	Nombre        string
	Facultad      string
	Semestre      int64
	NivelUrgencia string
}

type TicketAyuda struct {
	ID                int64
	SolicitanteID     int64
	DispositivoID     int64
	DescripcionFalla  string
	SoftwareRequerido string
	EstadoTicket      string
}

type Usuario struct {
	ID       int64
	Email    string
	Password string
	Rol      string
}
