// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarDispositivo = `-- name: ActualizarDispositivo :one
UPDATE dispositivos
SET solicitante_id = ?, marca = ?, modelo = ?, tipo_almacenamiento = ?, ram_gb = ?, sistema_operativo = ?
WHERE id = ?
RETURNING id, solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo
`

type ActualizarDispositivoParams struct {
	SolicitanteID      int64
	Marca              string
	Modelo             string
	TipoAlmacenamiento string
	RamGb              int64
	SistemaOperativo   string
	ID                 int64
}

func (q *Queries) ActualizarDispositivo(ctx context.Context, arg ActualizarDispositivoParams) (Dispositivo, error) {
	row := q.db.QueryRowContext(ctx, actualizarDispositivo,
		arg.SolicitanteID,
		arg.Marca,
		arg.Modelo,
		arg.TipoAlmacenamiento,
		arg.RamGb,
		arg.SistemaOperativo,
		arg.ID,
	)
	var i Dispositivo
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.Marca,
		&i.Modelo,
		&i.TipoAlmacenamiento,
		&i.RamGb,
		&i.SistemaOperativo,
	)
	return i, err
}

const actualizarSolicitante = `-- name: ActualizarSolicitante :one
UPDATE solicitantes
SET nombre = ?, facultad = ?, semestre = ?, nivel_urgencia = ?
WHERE id = ?
RETURNING id, nombre, facultad, semestre, nivel_urgencia
`

type ActualizarSolicitanteParams struct {
	Nombre        string
	Facultad      string
	Semestre      int64
	NivelUrgencia string
	ID            int64
}

func (q *Queries) ActualizarSolicitante(ctx context.Context, arg ActualizarSolicitanteParams) (Solicitante, error) {
	row := q.db.QueryRowContext(ctx, actualizarSolicitante,
		arg.Nombre,
		arg.Facultad,
		arg.Semestre,
		arg.NivelUrgencia,
		arg.ID,
	)
	var i Solicitante
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Facultad,
		&i.Semestre,
		&i.NivelUrgencia,
	)
	return i, err
}

const actualizarTicketAyuda = `-- name: ActualizarTicketAyuda :one
UPDATE ticket_ayudas
SET solicitante_id = ?, dispositivo_id = ?, descripcion_falla = ?, software_requerido = ?, estado_ticket = ?
WHERE id = ?
RETURNING id, solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket
`

type ActualizarTicketAyudaParams struct {
	SolicitanteID     int64
	DispositivoID     int64
	DescripcionFalla  string
	SoftwareRequerido string
	EstadoTicket      string
	ID                int64
}

func (q *Queries) ActualizarTicketAyuda(ctx context.Context, arg ActualizarTicketAyudaParams) (TicketAyuda, error) {
	row := q.db.QueryRowContext(ctx, actualizarTicketAyuda,
		arg.SolicitanteID,
		arg.DispositivoID,
		arg.DescripcionFalla,
		arg.SoftwareRequerido,
		arg.EstadoTicket,
		arg.ID,
	)
	var i TicketAyuda
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.DispositivoID,
		&i.DescripcionFalla,
		&i.SoftwareRequerido,
		&i.EstadoTicket,
	)
	return i, err
}

const borrarDispositivo = `-- name: BorrarDispositivo :execrows
DELETE FROM dispositivos WHERE id = ?
`

func (q *Queries) BorrarDispositivo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarDispositivo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarSolicitante = `-- name: BorrarSolicitante :execrows
DELETE FROM solicitantes WHERE id = ?
`

func (q *Queries) BorrarSolicitante(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSolicitante, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarTicketAyuda = `-- name: BorrarTicketAyuda :execrows
DELETE FROM ticket_ayudas WHERE id = ?
`

func (q *Queries) BorrarTicketAyuda(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarTicketAyuda, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarDispositivoPorID = `-- name: BuscarDispositivoPorID :one
SELECT id, solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo FROM dispositivos
WHERE id = ?
`

func (q *Queries) BuscarDispositivoPorID(ctx context.Context, id int64) (Dispositivo, error) {
	row := q.db.QueryRowContext(ctx, buscarDispositivoPorID, id)
	var i Dispositivo
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.Marca,
		&i.Modelo,
		&i.TipoAlmacenamiento,
		&i.RamGb,
		&i.SistemaOperativo,
	)
	return i, err
}

const buscarSolicitantePorID = `-- name: BuscarSolicitantePorID :one
SELECT id, nombre, facultad, semestre, nivel_urgencia FROM solicitantes
WHERE id = ?
`

func (q *Queries) BuscarSolicitantePorID(ctx context.Context, id int64) (Solicitante, error) {
	row := q.db.QueryRowContext(ctx, buscarSolicitantePorID, id)
	var i Solicitante
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Facultad,
		&i.Semestre,
		&i.NivelUrgencia,
	)
	return i, err
}

const buscarTicketAyudaPorID = `-- name: BuscarTicketAyudaPorID :one
SELECT id, solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket FROM ticket_ayudas
WHERE id = ?
`

func (q *Queries) BuscarTicketAyudaPorID(ctx context.Context, id int64) (TicketAyuda, error) {
	row := q.db.QueryRowContext(ctx, buscarTicketAyudaPorID, id)
	var i TicketAyuda
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.DispositivoID,
		&i.DescripcionFalla,
		&i.SoftwareRequerido,
		&i.EstadoTicket,
	)
	return i, err
}

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :one
SELECT id, email, password, rol FROM usuarios
WHERE email = ?
`

func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, buscarUsuarioPorEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Rol,
	)
	return i, err
}

const crearDispositivo = `-- name: CrearDispositivo :one
INSERT INTO dispositivos (solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo
`

type CrearDispositivoParams struct {
	SolicitanteID      int64
	Marca              string
	Modelo             string
	TipoAlmacenamiento string
	RamGb              int64
	SistemaOperativo   string
}

func (q *Queries) CrearDispositivo(ctx context.Context, arg CrearDispositivoParams) (Dispositivo, error) {
	row := q.db.QueryRowContext(ctx, crearDispositivo,
		arg.SolicitanteID,
		arg.Marca,
		arg.Modelo,
		arg.TipoAlmacenamiento,
		arg.RamGb,
		arg.SistemaOperativo,
	)
	var i Dispositivo
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.Marca,
		&i.Modelo,
		&i.TipoAlmacenamiento,
		&i.RamGb,
		&i.SistemaOperativo,
	)
	return i, err
}

const crearSolicitante = `-- name: CrearSolicitante :one
INSERT INTO solicitantes (nombre, facultad, semestre, nivel_urgencia)
VALUES (?, ?, ?, ?)
RETURNING id, nombre, facultad, semestre, nivel_urgencia
`

type CrearSolicitanteParams struct {
	Nombre        string
	Facultad      string
	Semestre      int64
	NivelUrgencia string
}

func (q *Queries) CrearSolicitante(ctx context.Context, arg CrearSolicitanteParams) (Solicitante, error) {
	row := q.db.QueryRowContext(ctx, crearSolicitante,
		arg.Nombre,
		arg.Facultad,
		arg.Semestre,
		arg.NivelUrgencia,
	)
	var i Solicitante
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Facultad,
		&i.Semestre,
		&i.NivelUrgencia,
	)
	return i, err
}

const crearTicketAyuda = `-- name: CrearTicketAyuda :one
INSERT INTO ticket_ayudas (solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket)
VALUES (?, ?, ?, ?, ?)
RETURNING id, solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket
`

type CrearTicketAyudaParams struct {
	SolicitanteID     int64
	DispositivoID     int64
	DescripcionFalla  string
	SoftwareRequerido string
	EstadoTicket      string
}

func (q *Queries) CrearTicketAyuda(ctx context.Context, arg CrearTicketAyudaParams) (TicketAyuda, error) {
	row := q.db.QueryRowContext(ctx, crearTicketAyuda,
		arg.SolicitanteID,
		arg.DispositivoID,
		arg.DescripcionFalla,
		arg.SoftwareRequerido,
		arg.EstadoTicket,
	)
	var i TicketAyuda
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.DispositivoID,
		&i.DescripcionFalla,
		&i.SoftwareRequerido,
		&i.EstadoTicket,
	)
	return i, err
}

const crearUsuario = `-- name: CrearUsuario :one

INSERT INTO usuarios (email, password, rol)
VALUES (?, ?, ?)
RETURNING id, email, password, rol
`

type CrearUsuarioParams struct {
	Email    string
	Password string
	Rol      string
}

// ===================== USUARIOS =====================
func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, crearUsuario, arg.Email, arg.Password, arg.Rol)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Rol,
	)
	return i, err
}

const listarDispositivos = `-- name: ListarDispositivos :many

SELECT id, solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo FROM dispositivos
`

// ===================== DISPOSITIVOS =====================
func (q *Queries) ListarDispositivos(ctx context.Context) ([]Dispositivo, error) {
	rows, err := q.db.QueryContext(ctx, listarDispositivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispositivo
	for rows.Next() {
		var i Dispositivo
		if err := rows.Scan(
			&i.ID,
			&i.SolicitanteID,
			&i.Marca,
			&i.Modelo,
			&i.TipoAlmacenamiento,
			&i.RamGb,
			&i.SistemaOperativo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSolicitantes = `-- name: ListarSolicitantes :many

SELECT id, nombre, facultad, semestre, nivel_urgencia FROM solicitantes
`

// ===================== SOLICITANTES =====================
func (q *Queries) ListarSolicitantes(ctx context.Context) ([]Solicitante, error) {
	rows, err := q.db.QueryContext(ctx, listarSolicitantes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solicitante
	for rows.Next() {
		var i Solicitante
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Facultad,
			&i.Semestre,
			&i.NivelUrgencia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarTicketAyudas = `-- name: ListarTicketAyudas :many

SELECT id, solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket FROM ticket_ayudas
`

// ===================== TICKET_AYUDAS =====================
func (q *Queries) ListarTicketAyudas(ctx context.Context) ([]TicketAyuda, error) {
	rows, err := q.db.QueryContext(ctx, listarTicketAyudas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketAyuda
	for rows.Next() {
		var i TicketAyuda
		if err := rows.Scan(
			&i.ID,
			&i.SolicitanteID,
			&i.DispositivoID,
			&i.DescripcionFalla,
			&i.SoftwareRequerido,
			&i.EstadoTicket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
