// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type Citum struct {
	ID             int64
	SolicitanteID  string
	TecnicoID      string
	Estado         string
	HoraAcordada   string
	PuntoEncuentro string
}

type PuntoEncuentro struct {
	ID                    int64
	NombreLugar           string
	FacultadPerteneciente string
	DisponibleParaSoporte bool
}

type Soporte struct {
	ID              int64
	CitaID          int64
	DispositivoID   int64
	Solucion        string
	PiezasCambiadas string
}
