// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarCita = `-- name: ActualizarCita :one
UPDATE cita
SET solicitante_id = ?, tecnico_id = ?, estado = ?, hora_acordada = ?, punto_encuentro = ?
WHERE id = ?
RETURNING id, solicitante_id, tecnico_id, estado, hora_acordada, punto_encuentro
`

type ActualizarCitaParams struct {
	SolicitanteID  string
	TecnicoID      string
	Estado         string
	HoraAcordada   string
	PuntoEncuentro string
	ID             int64
}

func (q *Queries) ActualizarCita(ctx context.Context, arg ActualizarCitaParams) (Citum, error) {
	row := q.db.QueryRowContext(ctx, actualizarCita,
		arg.SolicitanteID,
		arg.TecnicoID,
		arg.Estado,
		arg.HoraAcordada,
		arg.PuntoEncuentro,
		arg.ID,
	)
	var i Citum
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.TecnicoID,
		&i.Estado,
		&i.HoraAcordada,
		&i.PuntoEncuentro,
	)
	return i, err
}

const actualizarPuntoEncuentro = `-- name: ActualizarPuntoEncuentro :one
UPDATE punto_encuentros
SET nombre_lugar = ?, facultad_perteneciente = ?, disponible_para_soporte = ?
WHERE id = ?
RETURNING id, nombre_lugar, facultad_perteneciente, disponible_para_soporte
`

type ActualizarPuntoEncuentroParams struct {
	NombreLugar           string
	FacultadPerteneciente string
	DisponibleParaSoporte bool
	ID                    int64
}

func (q *Queries) ActualizarPuntoEncuentro(ctx context.Context, arg ActualizarPuntoEncuentroParams) (PuntoEncuentro, error) {
	row := q.db.QueryRowContext(ctx, actualizarPuntoEncuentro,
		arg.NombreLugar,
		arg.FacultadPerteneciente,
		arg.DisponibleParaSoporte,
		arg.ID,
	)
	var i PuntoEncuentro
	err := row.Scan(
		&i.ID,
		&i.NombreLugar,
		&i.FacultadPerteneciente,
		&i.DisponibleParaSoporte,
	)
	return i, err
}

const actualizarSoporte = `-- name: ActualizarSoporte :one
UPDATE soportes
SET cita_id = ?, dispositivo_id = ?, solucion = ?, piezas_cambiadas = ?
WHERE id = ?
RETURNING id, cita_id, dispositivo_id, solucion, piezas_cambiadas
`

type ActualizarSoporteParams struct {
	CitaID          int64
	DispositivoID   int64
	Solucion        string
	PiezasCambiadas string
	ID              int64
}

func (q *Queries) ActualizarSoporte(ctx context.Context, arg ActualizarSoporteParams) (Soporte, error) {
	row := q.db.QueryRowContext(ctx, actualizarSoporte,
		arg.CitaID,
		arg.DispositivoID,
		arg.Solucion,
		arg.PiezasCambiadas,
		arg.ID,
	)
	var i Soporte
	err := row.Scan(
		&i.ID,
		&i.CitaID,
		&i.DispositivoID,
		&i.Solucion,
		&i.PiezasCambiadas,
	)
	return i, err
}

const borrarCita = `-- name: BorrarCita :execrows
DELETE FROM cita WHERE id = ?
`

func (q *Queries) BorrarCita(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarCita, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarPuntoEncuentro = `-- name: BorrarPuntoEncuentro :execrows
DELETE FROM punto_encuentros WHERE id = ?
`

func (q *Queries) BorrarPuntoEncuentro(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarPuntoEncuentro, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarSoporte = `-- name: BorrarSoporte :execrows
DELETE FROM soportes WHERE id = ?
`

func (q *Queries) BorrarSoporte(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSoporte, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarCitaPorID = `-- name: BuscarCitaPorID :one
SELECT id, solicitante_id, tecnico_id, estado, hora_acordada, punto_encuentro FROM cita
WHERE id = ?
`

func (q *Queries) BuscarCitaPorID(ctx context.Context, id int64) (Citum, error) {
	row := q.db.QueryRowContext(ctx, buscarCitaPorID, id)
	var i Citum
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.TecnicoID,
		&i.Estado,
		&i.HoraAcordada,
		&i.PuntoEncuentro,
	)
	return i, err
}

const buscarPuntoEncuentroPorID = `-- name: BuscarPuntoEncuentroPorID :one
SELECT id, nombre_lugar, facultad_perteneciente, disponible_para_soporte FROM punto_encuentros
WHERE id = ?
`

func (q *Queries) BuscarPuntoEncuentroPorID(ctx context.Context, id int64) (PuntoEncuentro, error) {
	row := q.db.QueryRowContext(ctx, buscarPuntoEncuentroPorID, id)
	var i PuntoEncuentro
	err := row.Scan(
		&i.ID,
		&i.NombreLugar,
		&i.FacultadPerteneciente,
		&i.DisponibleParaSoporte,
	)
	return i, err
}

const buscarSoportePorID = `-- name: BuscarSoportePorID :one
SELECT id, cita_id, dispositivo_id, solucion, piezas_cambiadas FROM soportes
WHERE id = ?
`

func (q *Queries) BuscarSoportePorID(ctx context.Context, id int64) (Soporte, error) {
	row := q.db.QueryRowContext(ctx, buscarSoportePorID, id)
	var i Soporte
	err := row.Scan(
		&i.ID,
		&i.CitaID,
		&i.DispositivoID,
		&i.Solucion,
		&i.PiezasCambiadas,
	)
	return i, err
}

const crearCita = `-- name: CrearCita :one
INSERT INTO cita (solicitante_id, tecnico_id, estado, hora_acordada, punto_encuentro)
VALUES (?, ?, ?, ?, ?)
RETURNING id, solicitante_id, tecnico_id, estado, hora_acordada, punto_encuentro
`

type CrearCitaParams struct {
	SolicitanteID  string
	TecnicoID      string
	Estado         string
	HoraAcordada   string
	PuntoEncuentro string
}

func (q *Queries) CrearCita(ctx context.Context, arg CrearCitaParams) (Citum, error) {
	row := q.db.QueryRowContext(ctx, crearCita,
		arg.SolicitanteID,
		arg.TecnicoID,
		arg.Estado,
		arg.HoraAcordada,
		arg.PuntoEncuentro,
	)
	var i Citum
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.TecnicoID,
		&i.Estado,
		&i.HoraAcordada,
		&i.PuntoEncuentro,
	)
	return i, err
}

const crearPuntoEncuentro = `-- name: CrearPuntoEncuentro :one
INSERT INTO punto_encuentros (nombre_lugar, facultad_perteneciente, disponible_para_soporte)
VALUES (?, ?, ?)
RETURNING id, nombre_lugar, facultad_perteneciente, disponible_para_soporte
`

type CrearPuntoEncuentroParams struct {
	NombreLugar           string
	FacultadPerteneciente string
	DisponibleParaSoporte bool
}

func (q *Queries) CrearPuntoEncuentro(ctx context.Context, arg CrearPuntoEncuentroParams) (PuntoEncuentro, error) {
	row := q.db.QueryRowContext(ctx, crearPuntoEncuentro, arg.NombreLugar, arg.FacultadPerteneciente, arg.DisponibleParaSoporte)
	var i PuntoEncuentro
	err := row.Scan(
		&i.ID,
		&i.NombreLugar,
		&i.FacultadPerteneciente,
		&i.DisponibleParaSoporte,
	)
	return i, err
}

const crearSoporte = `-- name: CrearSoporte :one
INSERT INTO soportes (cita_id, dispositivo_id, solucion, piezas_cambiadas)
VALUES (?, ?, ?, ?)
RETURNING id, cita_id, dispositivo_id, solucion, piezas_cambiadas
`

type CrearSoporteParams struct {
	CitaID          int64
	DispositivoID   int64
	Solucion        string
	PiezasCambiadas string
}

func (q *Queries) CrearSoporte(ctx context.Context, arg CrearSoporteParams) (Soporte, error) {
	row := q.db.QueryRowContext(ctx, crearSoporte,
		arg.CitaID,
		arg.DispositivoID,
		arg.Solucion,
		arg.PiezasCambiadas,
	)
	var i Soporte
	err := row.Scan(
		&i.ID,
		&i.CitaID,
		&i.DispositivoID,
		&i.Solucion,
		&i.PiezasCambiadas,
	)
	return i, err
}

const listarCitas = `-- name: ListarCitas :many

SELECT id, solicitante_id, tecnico_id, estado, hora_acordada, punto_encuentro FROM cita
`

// ===================== CITAS =====================
func (q *Queries) ListarCitas(ctx context.Context) ([]Citum, error) {
	rows, err := q.db.QueryContext(ctx, listarCitas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Citum
	for rows.Next() {
		var i Citum
		if err := rows.Scan(
			&i.ID,
			&i.SolicitanteID,
			&i.TecnicoID,
			&i.Estado,
			&i.HoraAcordada,
			&i.PuntoEncuentro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPuntosEncuentro = `-- name: ListarPuntosEncuentro :many

SELECT id, nombre_lugar, facultad_perteneciente, disponible_para_soporte FROM punto_encuentros
`

// ===================== PUNTOS DE ENCUENTRO =====================
func (q *Queries) ListarPuntosEncuentro(ctx context.Context) ([]PuntoEncuentro, error) {
	rows, err := q.db.QueryContext(ctx, listarPuntosEncuentro)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PuntoEncuentro
	for rows.Next() {
		var i PuntoEncuentro
		if err := rows.Scan(
			&i.ID,
			&i.NombreLugar,
			&i.FacultadPerteneciente,
			&i.DisponibleParaSoporte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSoportes = `-- name: ListarSoportes :many

SELECT id, cita_id, dispositivo_id, solucion, piezas_cambiadas FROM soportes
`

// ===================== SOPORTES =====================
func (q *Queries) ListarSoportes(ctx context.Context) ([]Soporte, error) {
	rows, err := q.db.QueryContext(ctx, listarSoportes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Soporte
	for rows.Next() {
		var i Soporte
		if err := rows.Scan(
			&i.ID,
			&i.CitaID,
			&i.DispositivoID,
			&i.Solucion,
			&i.PiezasCambiadas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
