// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type HorarioTecnico struct {
	ID                   int64
	TecnicoID            int64
	DiaSemana            string
	HoraInicio           string
	HoraFin              string
	EstadoDisponibilidad string
}

type ServicioOfrecido struct {
	ID               int64
	TecnicoID        int64
	NombreServicio   string
	NivelExperiencia string
	TiempoEstimado   string
}

type Tecnico struct {
	ID         int64
	Nombre     string
	Reputacion float64
}
