// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarTecnico = `-- name: ActualizarTecnico :one
UPDATE tecnicos SET nombre = ?, reputacion = ? WHERE id = ? RETURNING id, nombre, reputacion
`

type ActualizarTecnicoParams struct {
	Nombre     string
	Reputacion float64
	ID         int64
}

func (q *Queries) ActualizarTecnico(ctx context.Context, arg ActualizarTecnicoParams) (Tecnico, error) {
	row := q.db.QueryRowContext(ctx, actualizarTecnico, arg.Nombre, arg.Reputacion, arg.ID)
	var i Tecnico
	err := row.Scan(&i.ID, &i.Nombre, &i.Reputacion)
	return i, err
}

const borrarHorariosPorTecnico = `-- name: BorrarHorariosPorTecnico :exec
DELETE FROM horario_tecnicos WHERE tecnico_id = ?
`

func (q *Queries) BorrarHorariosPorTecnico(ctx context.Context, tecnicoID int64) error {
	_, err := q.db.ExecContext(ctx, borrarHorariosPorTecnico, tecnicoID)
	return err
}

const borrarServiciosPorTecnico = `-- name: BorrarServiciosPorTecnico :exec
DELETE FROM servicio_ofrecidos WHERE tecnico_id = ?
`

func (q *Queries) BorrarServiciosPorTecnico(ctx context.Context, tecnicoID int64) error {
	_, err := q.db.ExecContext(ctx, borrarServiciosPorTecnico, tecnicoID)
	return err
}

const borrarTecnico = `-- name: BorrarTecnico :execrows
DELETE FROM tecnicos WHERE id = ?
`

func (q *Queries) BorrarTecnico(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarTecnico, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarTecnicoPorID = `-- name: BuscarTecnicoPorID :one
SELECT id, nombre, reputacion FROM tecnicos WHERE id = ?
`

func (q *Queries) BuscarTecnicoPorID(ctx context.Context, id int64) (Tecnico, error) {
	row := q.db.QueryRowContext(ctx, buscarTecnicoPorID, id)
	var i Tecnico
	err := row.Scan(&i.ID, &i.Nombre, &i.Reputacion)
	return i, err
}

const crearHorario = `-- name: CrearHorario :one
INSERT INTO horario_tecnicos (tecnico_id, dia_semana, hora_inicio, hora_fin, estado_disponibilidad) VALUES (?, ?, ?, ?, ?) RETURNING id, tecnico_id, dia_semana, hora_inicio, hora_fin, estado_disponibilidad
`

type CrearHorarioParams struct {
	TecnicoID            int64
	DiaSemana            string
	HoraInicio           string
	HoraFin              string
	EstadoDisponibilidad string
}

func (q *Queries) CrearHorario(ctx context.Context, arg CrearHorarioParams) (HorarioTecnico, error) {
	row := q.db.QueryRowContext(ctx, crearHorario,
		arg.TecnicoID,
		arg.DiaSemana,
		arg.HoraInicio,
		arg.HoraFin,
		arg.EstadoDisponibilidad,
	)
	var i HorarioTecnico
	err := row.Scan(
		&i.ID,
		&i.TecnicoID,
		&i.DiaSemana,
		&i.HoraInicio,
		&i.HoraFin,
		&i.EstadoDisponibilidad,
	)
	return i, err
}

const crearServicio = `-- name: CrearServicio :one
INSERT INTO servicio_ofrecidos (tecnico_id, nombre_servicio, nivel_experiencia, tiempo_estimado) VALUES (?, ?, ?, ?) RETURNING id, tecnico_id, nombre_servicio, nivel_experiencia, tiempo_estimado
`

type CrearServicioParams struct {
	TecnicoID        int64
	NombreServicio   string
	NivelExperiencia string
	TiempoEstimado   string
}

func (q *Queries) CrearServicio(ctx context.Context, arg CrearServicioParams) (ServicioOfrecido, error) {
	row := q.db.QueryRowContext(ctx, crearServicio,
		arg.TecnicoID,
		arg.NombreServicio,
		arg.NivelExperiencia,
		arg.TiempoEstimado,
	)
	var i ServicioOfrecido
	err := row.Scan(
		&i.ID,
		&i.TecnicoID,
		&i.NombreServicio,
		&i.NivelExperiencia,
		&i.TiempoEstimado,
	)
	return i, err
}

const crearTecnico = `-- name: CrearTecnico :one
INSERT INTO tecnicos (nombre, reputacion) VALUES (?, ?) RETURNING id, nombre, reputacion
`

type CrearTecnicoParams struct {
	Nombre     string
	Reputacion float64
}

func (q *Queries) CrearTecnico(ctx context.Context, arg CrearTecnicoParams) (Tecnico, error) {
	row := q.db.QueryRowContext(ctx, crearTecnico, arg.Nombre, arg.Reputacion)
	var i Tecnico
	err := row.Scan(&i.ID, &i.Nombre, &i.Reputacion)
	return i, err
}

const listarHorariosPorTecnico = `-- name: ListarHorariosPorTecnico :many
SELECT id, tecnico_id, dia_semana, hora_inicio, hora_fin, estado_disponibilidad FROM horario_tecnicos WHERE tecnico_id = ?
`

func (q *Queries) ListarHorariosPorTecnico(ctx context.Context, tecnicoID int64) ([]HorarioTecnico, error) {
	rows, err := q.db.QueryContext(ctx, listarHorariosPorTecnico, tecnicoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HorarioTecnico
	for rows.Next() {
		var i HorarioTecnico
		if err := rows.Scan(
			&i.ID,
			&i.TecnicoID,
			&i.DiaSemana,
			&i.HoraInicio,
			&i.HoraFin,
			&i.EstadoDisponibilidad,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarServiciosPorTecnico = `-- name: ListarServiciosPorTecnico :many
SELECT id, tecnico_id, nombre_servicio, nivel_experiencia, tiempo_estimado FROM servicio_ofrecidos WHERE tecnico_id = ?
`

func (q *Queries) ListarServiciosPorTecnico(ctx context.Context, tecnicoID int64) ([]ServicioOfrecido, error) {
	rows, err := q.db.QueryContext(ctx, listarServiciosPorTecnico, tecnicoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServicioOfrecido
	for rows.Next() {
		var i ServicioOfrecido
		if err := rows.Scan(
			&i.ID,
			&i.TecnicoID,
			&i.NombreServicio,
			&i.NivelExperiencia,
			&i.TiempoEstimado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarTecnicos = `-- name: ListarTecnicos :many
SELECT id, nombre, reputacion FROM tecnicos
`

func (q *Queries) ListarTecnicos(ctx context.Context) ([]Tecnico, error) {
	rows, err := q.db.QueryContext(ctx, listarTecnicos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tecnico
	for rows.Next() {
		var i Tecnico
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Reputacion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
