// Code generated by sqlc. DO NOT EDIT.
// Equivalente a la salida de `sqlc generate` (engine sqlite, sql_package database/sql).
package sqlcdb

import (
	"context"
	"database/sql"
)

// DBTX es lo que sqlc necesita para hablar con la base: lo cumple tanto *sql.DB
// como *sql.Tx. Por eso New() recibe una interfaz y no un tipo concreto.
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}
