// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql
package sqlcdb

import "context"

const actualizarDispositivo = `-- name: ActualizarDispositivo :one
UPDATE dispositivos
SET marca = ?, modelo = ?, tipo_almacenamiento = ?, ram_gb = ?, sistema_operativo = ?
WHERE id = ?
RETURNING id, solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo
`

type ActualizarDispositivoParams struct {
	Marca              string
	Modelo             string
	TipoAlmacenamiento string
	RamGb              int64
	SistemaOperativo   string
	ID                 int64
}

func (q *Queries) ActualizarDispositivo(ctx context.Context, arg ActualizarDispositivoParams) (Dispositivo, error) {
	row := q.db.QueryRowContext(ctx, actualizarDispositivo,
		arg.Marca,
		arg.Modelo,
		arg.TipoAlmacenamiento,
		arg.RamGb,
		arg.SistemaOperativo,
		arg.ID,
	)
	var i Dispositivo
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.Marca,
		&i.Modelo,
		&i.TipoAlmacenamiento,
		&i.RamGb,
		&i.SistemaOperativo,
	)
	return i, err
}

const borrarDispositivo = `-- name: BorrarDispositivo :execrows
DELETE FROM dispositivos WHERE id = ?
`

func (q *Queries) BorrarDispositivo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarDispositivo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarDispositivoPorID = `-- name: BuscarDispositivoPorID :one
SELECT id, solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo FROM dispositivos
WHERE id = ?
`

func (q *Queries) BuscarDispositivoPorID(ctx context.Context, id int64) (Dispositivo, error) {
	row := q.db.QueryRowContext(ctx, buscarDispositivoPorID, id)
	var i Dispositivo
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.Marca,
		&i.Modelo,
		&i.TipoAlmacenamiento,
		&i.RamGb,
		&i.SistemaOperativo,
	)
	return i, err
}

const crearDispositivo = `-- name: CrearDispositivo :one
INSERT INTO dispositivos (solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo
`

type CrearDispositivoParams struct {
	SolicitanteID      int64
	Marca              string
	Modelo             string
	TipoAlmacenamiento string
	RamGb              int64
	SistemaOperativo   string
}

func (q *Queries) CrearDispositivo(ctx context.Context, arg CrearDispositivoParams) (Dispositivo, error) {
	row := q.db.QueryRowContext(ctx, crearDispositivo,
		arg.SolicitanteID,
		arg.Marca,
		arg.Modelo,
		arg.TipoAlmacenamiento,
		arg.RamGb,
		arg.SistemaOperativo,
	)
	var i Dispositivo
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.Marca,
		&i.Modelo,
		&i.TipoAlmacenamiento,
		&i.RamGb,
		&i.SistemaOperativo,
	)
	return i, err
}

const listarDispositivos = `-- name: ListarDispositivos :many
SELECT id, solicitante_id, marca, modelo, tipo_almacenamiento, ram_gb, sistema_operativo FROM dispositivos
`

func (q *Queries) ListarDispositivos(ctx context.Context) ([]Dispositivo, error) {
	rows, err := q.db.QueryContext(ctx, listarDispositivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispositivo
	for rows.Next() {
		var i Dispositivo
		if err := rows.Scan(
			&i.ID,
			&i.SolicitanteID,
			&i.Marca,
			&i.Modelo,
			&i.TipoAlmacenamiento,
			&i.RamGb,
			&i.SistemaOperativo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
