// Code generated by sqlc. DO NOT EDIT.
package sqlcdb

// Estos structs los genera sqlc a partir de db/schema.sql. OJO: NO son los
// models del dominio. Fíjense en los tipos: todos los enteros son int64 (no
// int). Esa diferencia es la razón por la que el adaptador tiene que MAPEAR.

type Solicitante struct {
	ID            int64
	UsuarioID     int64
	Matricula     string
	Nombre        string
	Facultad      string
	Semestre      int64
	NivelUrgencia string
}

type Dispositivo struct {
	ID                 int64
	SolicitanteID      int64
	Marca              string
	Modelo             string
	TipoAlmacenamiento string
	RamGb              int64
	SistemaOperativo   string
}

type TicketAyuda struct {
	ID                int64
	SolicitanteID     int64
	DispositivoID     int64
	DescripcionFalla  string
	SoftwareRequerido string
	EstadoTicket      string
}
