// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql
package sqlcdb

import "context"

const actualizarSolicitante = `-- name: ActualizarSolicitante :one
UPDATE solicitantes
SET matricula = ?, nombre = ?, facultad = ?, semestre = ?, nivel_urgencia = ?
WHERE id = ?
RETURNING id, usuario_id, matricula, nombre, facultad, semestre, nivel_urgencia
`

type ActualizarSolicitanteParams struct {
	Matricula     string
	Nombre        string
	Facultad      string
	Semestre      int64
	NivelUrgencia string
	ID            int64
}

func (q *Queries) ActualizarSolicitante(ctx context.Context, arg ActualizarSolicitanteParams) (Solicitante, error) {
	row := q.db.QueryRowContext(ctx, actualizarSolicitante,
		arg.Matricula,
		arg.Nombre,
		arg.Facultad,
		arg.Semestre,
		arg.NivelUrgencia,
		arg.ID,
	)
	var i Solicitante
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Matricula,
		&i.Nombre,
		&i.Facultad,
		&i.Semestre,
		&i.NivelUrgencia,
	)
	return i, err
}

const borrarSolicitante = `-- name: BorrarSolicitante :execrows
DELETE FROM solicitantes WHERE id = ?
`

func (q *Queries) BorrarSolicitante(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSolicitante, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarSolicitantePorID = `-- name: BuscarSolicitantePorID :one
SELECT id, usuario_id, matricula, nombre, facultad, semestre, nivel_urgencia FROM solicitantes
WHERE id = ?
`

func (q *Queries) BuscarSolicitantePorID(ctx context.Context, id int64) (Solicitante, error) {
	row := q.db.QueryRowContext(ctx, buscarSolicitantePorID, id)
	var i Solicitante
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Matricula,
		&i.Nombre,
		&i.Facultad,
		&i.Semestre,
		&i.NivelUrgencia,
	)
	return i, err
}

const crearSolicitante = `-- name: CrearSolicitante :one
INSERT INTO solicitantes (usuario_id, matricula, nombre, facultad, semestre, nivel_urgencia)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, usuario_id, matricula, nombre, facultad, semestre, nivel_urgencia
`

type CrearSolicitanteParams struct {
	UsuarioID     int64
	Matricula     string
	Nombre        string
	Facultad      string
	Semestre      int64
	NivelUrgencia string
}

func (q *Queries) CrearSolicitante(ctx context.Context, arg CrearSolicitanteParams) (Solicitante, error) {
	row := q.db.QueryRowContext(ctx, crearSolicitante,
		arg.UsuarioID,
		arg.Matricula,
		arg.Nombre,
		arg.Facultad,
		arg.Semestre,
		arg.NivelUrgencia,
	)
	var i Solicitante
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Matricula,
		&i.Nombre,
		&i.Facultad,
		&i.Semestre,
		&i.NivelUrgencia,
	)
	return i, err
}

const listarSolicitantes = `-- name: ListarSolicitantes :many
SELECT id, usuario_id, matricula, nombre, facultad, semestre, nivel_urgencia FROM solicitantes
`

func (q *Queries) ListarSolicitantes(ctx context.Context) ([]Solicitante, error) {
	rows, err := q.db.QueryContext(ctx, listarSolicitantes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solicitante
	for rows.Next() {
		var i Solicitante
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Matricula,
			&i.Nombre,
			&i.Facultad,
			&i.Semestre,
			&i.NivelUrgencia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
