// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql
package sqlcdb

import "context"

const actualizarTicketAyuda = `-- name: ActualizarTicketAyuda :one
UPDATE ticket_ayudas
SET dispositivo_id = ?, descripcion_falla = ?, software_requerido = ?, estado_ticket = ?
WHERE id = ?
RETURNING id, solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket
`

type ActualizarTicketAyudaParams struct {
	DispositivoID     int64
	DescripcionFalla  string
	SoftwareRequerido string
	EstadoTicket      string
	ID                int64
}

func (q *Queries) ActualizarTicketAyuda(ctx context.Context, arg ActualizarTicketAyudaParams) (TicketAyuda, error) {
	row := q.db.QueryRowContext(ctx, actualizarTicketAyuda,
		arg.DispositivoID,
		arg.DescripcionFalla,
		arg.SoftwareRequerido,
		arg.EstadoTicket,
		arg.ID,
	)
	var i TicketAyuda
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.DispositivoID,
		&i.DescripcionFalla,
		&i.SoftwareRequerido,
		&i.EstadoTicket,
	)
	return i, err
}

const borrarTicketAyuda = `-- name: BorrarTicketAyuda :execrows
DELETE FROM ticket_ayudas WHERE id = ?
`

func (q *Queries) BorrarTicketAyuda(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarTicketAyuda, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarTicketAyudaPorID = `-- name: BuscarTicketAyudaPorID :one
SELECT id, solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket FROM ticket_ayudas
WHERE id = ?
`

func (q *Queries) BuscarTicketAyudaPorID(ctx context.Context, id int64) (TicketAyuda, error) {
	row := q.db.QueryRowContext(ctx, buscarTicketAyudaPorID, id)
	var i TicketAyuda
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.DispositivoID,
		&i.DescripcionFalla,
		&i.SoftwareRequerido,
		&i.EstadoTicket,
	)
	return i, err
}

const crearTicketAyuda = `-- name: CrearTicketAyuda :one
INSERT INTO ticket_ayudas (solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket)
VALUES (?, ?, ?, ?, ?)
RETURNING id, solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket
`

type CrearTicketAyudaParams struct {
	SolicitanteID     int64
	DispositivoID     int64
	DescripcionFalla  string
	SoftwareRequerido string
	EstadoTicket      string
}

func (q *Queries) CrearTicketAyuda(ctx context.Context, arg CrearTicketAyudaParams) (TicketAyuda, error) {
	row := q.db.QueryRowContext(ctx, crearTicketAyuda,
		arg.SolicitanteID,
		arg.DispositivoID,
		arg.DescripcionFalla,
		arg.SoftwareRequerido,
		arg.EstadoTicket,
	)
	var i TicketAyuda
	err := row.Scan(
		&i.ID,
		&i.SolicitanteID,
		&i.DispositivoID,
		&i.DescripcionFalla,
		&i.SoftwareRequerido,
		&i.EstadoTicket,
	)
	return i, err
}

const listarTicketAyudas = `-- name: ListarTicketAyudas :many
SELECT id, solicitante_id, dispositivo_id, descripcion_falla, software_requerido, estado_ticket FROM ticket_ayudas
`

func (q *Queries) ListarTicketAyudas(ctx context.Context) ([]TicketAyuda, error) {
	rows, err := q.db.QueryContext(ctx, listarTicketAyudas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketAyuda
	for rows.Next() {
		var i TicketAyuda
		if err := rows.Scan(
			&i.ID,
			&i.SolicitanteID,
			&i.DispositivoID,
			&i.DescripcionFalla,
			&i.SoftwareRequerido,
			&i.EstadoTicket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
